[probe]
# probe_index
protocol = "Swd"
# speed

[flashing]
enabled = true
halt_afterwards = false
restore_unwritten_bytes = false
# flash_layout_output_path

[general]
# chip
chip_descriptions = []
log_level = "Error"
attach_under_reset = false

[rtt]
enabled = false
channels = [
    # { up = 0, down = 1 }
]
timeout = 3000

[gdb]
enabled = false
# gdb_connection_string